colored object age
hidetatz/kubecolor pull request #53
Opened 2021-03-21 08:13 UTC by witalisoft

## WHAT
Fresh object according to age is colored as green. Fresh threshold level is configurable value by setting environment variable, with default set as 5 minutes.

## WHY
It's much easier to figure out which objects are recently created ie. created by k8s hpa.

## Related issue (if exists)

2021-03-22 00:47 UTC, dty1er commented
@witalisoft 
Thank you for sending the PR.

While this feature looks interesting, I want to make the feature opt-in because users who are not aware of this feature might get confused why they are colored. I think it's better to disable this feature if the env var is empty.

Also, I want to start review with proper unit tests. Can you also work on that?

2021-03-22 08:33 UTC, witalisoft commented
Thanks for reply.

Sounds good to me.

2021-03-22 08:35 UTC, witalisoft commented
I've made changes according to your suggestion.

2021-04-27 02:31 UTC, dty1er requested changes
Sorry to be late.
Please change the error message to make it easy to understand how the error message is shown.

2021-04-27 02:31 UTC, dty1er commented on command/config.go
> +			fmt.Printf("cannot parse duration taken from env %s, err %v\n", objFreshAgeThresholdEnv, err)
```suggestion
			fmt.Printf("[WARN] [kubecolor] cannot parse duration taken from env %s. See kubecolor document. %v\n", objFreshAgeThresholdEnv, err)
```

2021-04-29 08:47 UTC, witalisoft commented
ok, I applied your suggestion

2021-05-12 08:01 UTC, witalisoft commented
ping

2022-09-28 15:43 UTC, prune998 commented
this patch was applied at https://github.com/kubecolor/kubecolor

2022-12-31 05:29 UTC, hidetatz commented
Closing now as it's stale.

2022-12-31 05:29 UTC, closed without merging